name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Get dependencies
      run: sudo apt-get install -y build-essential cmake
    - name: Build
      run: cd build && make
