name: C++ CI

on:
  push:
    branches: [ main, devel ]
  pull_request:
    branches: [ main, devel ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get dependencies
      run: sudo apt-get install -y build-essential cmake
    - name: Build
      run: mkdir build && cd build && cmake .. && make
